#' install R pacakges for GHA
install.packages(
  c(
    "remotes",
    "terra",
    "arrow",
    "remotes",
    "gghdx",
    "geoarrow",
    "sf",
    "ggplot2",
    "lubridate",
    "dplyr",
    "stringr",
    "gghdx",
    "tidyr",
    "readr",
    "logger",
    "glue",
    "logger",
    "blastula",
    "exactextractr",
    "rlang",
    "box",
    "zoo",
    "AzureStor",
    "logger"
    )
)
remotes::install_github("OCHA-DAP/cumulus")
