name: send-alert-email

on:
  workflow_dispatch:
      inputs:
        TEST_EMAIL:
          required: true
          type: choice
          default: "TRUE"
          options:
            - "TRUE"
            - "FALSE"  
  schedule:
    - cron: '30 15 * * *' # start at 8:10 AM run every 3 hours until midnight
    
jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Cache R dependencies
        id: cache-r-deps
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: R-dependency-cache-${{ hashFiles('.github/depends_email.R') }}
          
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxml2-dev \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev \
            libsodium-dev \
            libcurl4-openssl-dev
            
      - name: Install R dependencies
        if: steps.cache-r-deps.outputs.cache-hit != 'true'
        run: |
          Rscript .github/depends_email.R
          
       - name: Run monitor imerg R script
         run: Rscript ./src/monitor_imerg.R
         shell: bash
         env:
           DSCI_AZ_SAS_DEV: ${{ secrets.DSCI_AZ_SAS_DEV }}
           CHD_DS_EMAIL_USERNAME: ${{ secrets.CHD_DS_EMAIL_USERNAME }}
           CHD_DS_EMAIL_PASSWORD: ${{ secrets.CHD_DS_EMAIL_PASSWORD }}
           CHD_DS_HOST: ${{ secrets.CHD_DS_HOST }}
           CHD_DS_PORT: ${{ secrets.CHD_DS_PORT }}
           AZURE_SAS: ${{ secrets.AZURE_SAS }}
           AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
           TEST_EMAIL: ${{ inputs.TEST_EMAIL || 'FALSE' }}