# This workflow uses actions to automatically run the dry corridor drought trigger monitoring.
# script.

name: PAK 2025 Contingency Monitoring.

on:
  workflow_dispatch:
      inputs:
        TEST_EMAIL:
          required: true
          type: choice
          default: "TRUE"
          options:
            - "TRUE"
            - "FALSE"  
          
jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CHD_DS_EMAIL_USERNAME: ${{ secrets.DSCI_AWS_EMAIL_USERNAME }}
      CHD_DS_EMAIL_PASSWORD: ${{ secrets.DSCI_AWS_EMAIL_PASSWORD }}
      CHD_DS_HOST: ${{ secrets.DSCI_AWS_EMAIL_HOST }}
      CHD_DS_PORT: 465
      DSCI_AZ_BLOB_DEV_SAS: ${{ secrets.DSCI_AZ_BLOB_DEV_SAS }}
      DSCI_AZ_BLOB_PROD_SAS: ${{ secrets.DSCI_AZ_BLOB_PROD_SAS }}
      DS_AZ_DB_PROD_UID_WRITE: ${{ secrets.DSCI_AZ_DB_PROD_UID_WRITE }}
      DS_AZ_DB_PROD_HOST: ${{ secrets.DSCI_AZ_DB_PROD_HOST }}
      DS_AZ_DB_PROD_PW_WRITE: ${{ secrets.DSCI_AZ_DB_PROD_PW_WRITE }}
      DS_AZ_DB_PROD_NAME: ${{ secrets.DS_AZ_DB_PROD_NAME }}
      EMAIL_WHO: ${{ inputs.EMAIL_WHO || 'core_developer' }}
      
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DSCI_AZ_DB_PROD_UID }} 
          POSTGRES_PASSWORD: ${{ secrets.DSCI_AZ_DB_PROD_PW}}
          POSTGRES_DB: ${{ secrets.DSCI_AZ_DB_PROD_NAME }}
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxml2-dev \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev \
            libsodium-dev \
            libfreetype6-dev \
            libcurl4-openssl-dev
      
      - name: Cache R dependencies
        id: cache-r-deps
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: R-dependency-cache-${{ hashFiles('.github/depend_email.R') }}
      
      - name: Install R dependencies
        if: steps.cache-r-deps.outputs.cache-hit != 'true'
        run: |
          Rscript .github/depends_email.R
    
      # - name: Run R-script-test-env-vars
      #   shell: bash
      #   run: Rscript ./src/monitoring_2025/test_gha_settings.R

      - name: Run R-script- IMERG Pakistan
        shell: bash
        run: Rscript ./src/monitor_imerg_2025a.R