name: update-readme

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '10 8-23/3 * * *' # start at 8:10 AM run every 3 hours until midnight
  #   - cron: '0 0,3,6 * * *'   # then run at midnight, 3 am, 6 am
jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Cache R dependencies
        id: cache-r-deps
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: R-dependency-cache-${{ hashFiles('.github/depends_readme.R') }}
      
      - name: Install R dependencies
        if: steps.cache-r-deps.outputs.cache-hit != 'true'
        run: |
          Rscript .github/depends_readme.R

      - name: Knit README.Rmd to README.md
        run: |
          Rscript -e "rmarkdown::render('README.Rmd', output_file = 'README.md')"
        shell: Rscript {0}
        env:
          DSCI_AZ_SAS_DEV: ${{ secrets.DSCI_AZ_SAS_DEV }}

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README.md" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
